POST http://127.0.0.1:3000/login HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### ---------------------

GET http://127.0.0.1:4444/?aaa=1&bbb=jerry&age=20 HTTP/1.1

### ---------------------

GET http://127.0.0.1:3000/name HTTP/1.1
